### ISSUE TITLE
Capture App missing from Google Play store

### ISSUE THREAD

**Issue by yahsee** [dhis2/dhis2-android-capture-app#1398]
**Describe the bug**
The Capture App cannot be found in the Google Play store.

**To Reproduce**
1. The link from https://www.dhis2.org/app-store to the Capture App in the Google Play store (https://play.google.com/store/apps/details?id=com.dhis2) results in a URL not found error.
2. Searching within the Google Play store for "DHIS2" results only in listings for the legacy apps, not for the Capture App

**Comment by Balcan** [comment]
Hi @yahsee,

Google has removed the app from the store due to a COVID-19 reference in the app description. We are trying to have it restored as soon as possible but communications with Google are very slow.
We are updating this post in the CoP with any new info we have:
https://community.dhis2.org/t/dhis2-android-capture-app-temporarily-not-available-in-google-play/39232
