### ISSUE TITLE
Build issue No matching configuration of project :zxing-android was found.

### ISSUE THREAD

**Issue by jullll1979** [dhis2/dhis2-android-capture-app#2658]
Hello, 

I'm trying to build from 6.2 repo and always get an error  : 

Could not determine the dependencies of task ':app:compileDhisDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:dhisDebugCompileClasspath'.
   > Could not resolve project :zxing-android.
     Required by:
         project :app
      > No matching configuration of project :zxing-android was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'default' with value 'dhis', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Configuration 'ktlintRuleset':
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about default (required 'dhis')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')

zxing seems to make me crazy.
Any help is appreciated ;)

Have a great evening

Jullll

**Comment by Balcan** [comment]
Hi @jullll1979,

We had to add the zxing-android submodule in the project because we needed some improvements  that were not released at the time and this was the only way to achieve what we wanted.

Good news is that zxing has recently release its new version ([3.5.0](https://github.com/zxing/zxing/releases/tag/zxing-3.5.0)) and we are removing this submodule for the next patch release. In the mean time, to be able to build the project you can do any of these two options:

- Add a build.gradle file to the zxing-android submodule (under the zxing-core/core path). It only needs the line `apply plugin: 'java'`

- Remove the zxing-submodule and update zxing version to 3.5.0. You will need to remove any reference to the zxing-android submodule from the settings.gradle file, update the dependency.gradle to add the new zxing version and change the implementation of zxing in the app build.gradle.

Hope this will help. I will let you know when we have removed it anyway.

**Comment by Balcan** [comment]
@jullll1979 , the module have been removed in the **develop** branch

**Comment by jullll1979** [comment]
Thanks for the follow-up. By adding the config it was working fine ;).
I will sync the repo as you updated the develop branch.
Thanks for your help
